export const ROUTES = {
  home: '/',
  category: '/category',
  product: '/product',
  content: '/content',
  cart: '/cart',
  checkout: '/checkout',
  checkoutSuccess: '/checkout/success',
  checkoutFailed: '/checkout/failed',
  search: '/search',
  authLogin: '/login',
  authSignup: '/signup',
  authResetPassword: '/reset-password',
  authSetNewPassword: '/set-new-password',
  account: '/account',
  accountEdit: '/account/edit',
  accountOrders: '/account/orders',
  accountWishlist: '/account/wishlist',
  accountAddressNew: '/account/address/new',
  accountAddressList: '/account/address/list',
  accountAddressEdit: '/account/address/edit'
};
